import type { Metadata } from "next";
import { dir } from "i18next";
import { Inter } from "next/font/google";
import "../globals.css";
import { languages } from "../i18n/settings";
const inter = Inter({ subsets: ["latin"] });

import GA4Script from "@/service/ga/GA4Script";
import PageTransition from "@/components/common/PageTransition";

export async function generateStaticParams() {
  return languages.map((lang) => ({ lang }));
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type LayoutProps = {
  children: React.ReactNode;
  params: {
    lang: string;
  };
};

export default function RootLayout({ children, params }: LayoutProps) {
  return (
    <html lang={params.lang} dir={dir(params.lang)}>
      <body className={inter.className}>
        <GA4Script />
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
